name: PyPI

on:
  schedule:
    # Weekly tests 
    - cron: "0 2 * * 1"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macOS-latest, ubuntu-latest, windows-latest]      # TODO use this when macOS-latest becomes stable again
        # os: [macOS-13, ubuntu-latest, windows-latest]          # TODO macOS-13 fails when building scipy with pip
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install package from PyPI
        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          python -m pip install mlcolvar[test]
          pip list

      - name: Run tests
        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          pytest -v --pyargs mlcolvar.tests --cov=mlcolvar --cov-report=xml --color=yes
